spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/itcuc_news?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8&useSSL=true
    username: root
    password: root
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: mysql
    hibernate:
      ddl-auto: none
    open-in-view: true
  freemarker:
    cache: false
    charset: UTF-8
    suffix: .ftl
    prefix: /ftl/
  redis:
    host: 127.0.0.1
    port: 6379
    password:
server:
  port: 8880
